"""empty message

Revision ID: 4993cfc3f4b6
Revises: 
Create Date: 2019-07-28 20:58:01.856564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4993cfc3f4b6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language",
        sa.Column("id", sa.String(length=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "text_group",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "text_group_membership",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text_key", sa.String(length=255), nullable=False),
        sa.Column("group_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["text_group.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("text_key", "group_id", name="unique_text_key_group_id"),
    )
    op.create_table(
        "translated_text",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=True),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["language"], ["language.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "language", name="unique_key_language"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translated_text")
    op.drop_table("text_group_membership")
    op.drop_table("text_group")
    op.drop_table("language")
    # ### end Alembic commands ###
